### ISSUE TITLE
ESA MAL Implementation - Encoding of Wrapped Null Attributes

### ISSUE THREAD

**Issue by CesarCoelho** [SamCooper/JAVA_SPEC_RIDS#22]
I was testing the SPP and I found a bug with the encoding of nullable URIs which is very weird. 
URI wraps a String inside. 

So, instead of having: 
URI uri = null; 

I had: 

URI uri = new URI((String) null); 

This was a mistake happening from my code  that let's you wrap one field with URI or Strings directly. Because you have both signatures, It is ambiguous which one we want when we put a null in it and java picked the second case. (this part is not relevant) 
Now the important part is that String Encoding did manage to take care of this and it never threw an error. When I switched it to SPP Encoding, it did complain. 
This obviously breaks the concept of MO, where switching layers below shouldn't have any consequences on the upper layers. 

---

Hi Stefan and Sam, 

I have been testing again DLR's SPP implementation and I found a couple of things that differ from the ESA's transports and break the MO concept
1. If I encode a URI as URI uri = new URI((String) null); the SPP transport layer cannot handle and throws an exception. ESA's versions don't complain. I don't know which one is doing the right thing. 
## (...)

The MAL Java API shall throw an IllegalArgumentException in this case (3.3.9.5.3 MAL Java API MB). Please raise an issue against the ESA implementation.

**Comment by SamCooper** [comment]
Umm, you should raise the RID on the ESA implementation not on the Java API specification.
